language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - "rm large_output_test.py"
  - "rm surrealism.pyc"
  - "rm test_surrealism.pyc"
install:
  - "pip install coveralls"
  - "pip install nose"
script:
  - "sudo nosetests --with-coverage --cover-package=test_surrealism.py"
after_success:
  coveralls
