language: python
python:
  - "2.7"
  - "3.2"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=surrealism/__init__.py"
after_success:
  coveralls
