language: python
branches:
  only:
    - master
    - develop
python:
  - "2.7"
  - "3.2"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=test_surrealism.py"
after_success:
  coveralls
