language: python
python:
  - "3.2"
  - "3.3"
  - "2.7"
before_install:
  - "rm large_output_test.py"
install:
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=test_surrealism.py"
after_success:
  coveralls
